# Generated by Django 3.2.2 on 2021-05-23 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='field_name',
            field=models.URLField(blank=True, null=True),
        ),
    ]
