# Generated by Django 3.2.2 on 2021-05-23 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_field_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='field_name',
            new_name='url',
        ),
    ]
